version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1029
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5432:5432"

  app:
    image: myapp:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1029
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - db