version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1029
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1029
      DB_HOST: db
      DB_PORT: 5432
      KV_VIPER_FILE: /usr/local/bin/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["run", "service"]
